export default {
  proposalsCount: 340,
  speakersCount: 287,
  proposalsBySpeaker: '1.18',
  formatsCount: [
    { id: 'e56e30ab-be22-5055-9138-a86a3249c766', label: '📣 Conference', value: 214 },
    { id: 'fc2e9afb-3cba-5428-9214-c146862f2a52', label: '⚡️ Quickie', value: 110 },
    { id: 'bc4d1840-d260-5fb6-9e83-f1b0da239793', label: '💻 Codelab', value: 16 },
  ],
  categoriesCount: [
    { id: 'ef048dea-2728-54c5-9334-93d0cfe5d981', label: '💡 Discovery', value: 97 },
    { id: 'cf75cee3-5ee8-58de-ac77-6bb665a3463d', label: '🌍 Web', value: 68 },
    { id: '4fee2bdd-0cf4-5429-945c-42a422577ff5', label: '☁️ Cloud & DevOps', value: 68 },
    { id: '3e79596d-6302-5601-a027-901bff9e2692', label: '📝 Languages', value: 32 },
    { id: 'dfa320e4-1f9b-53ee-8c98-3ef48ba81013', label: '📱 Mobile & IoT', value: 31 },
    { id: 'c97cf20f-aba8-5bcd-9251-72f8c3c536c6', label: '🤖 BigData & AI', value: 18 },
    { id: '1e18bcfa-f91a-5ac0-b2f1-ee586837c398', label: '🐱‍💻 SECURITY', value: 18 },
    { id: 'b8f42b3e-d1d0-5212-bb39-9dfad1b01661', label: '💚 UX / UI', value: 8 },
  ],
  companiesCount: [
    { id: '', label: '', value: 64 },
    { id: 'zenika', label: 'zenika', value: 33 },
    { id: 'sfeir', label: 'sfeir', value: 25 },
    { id: 'wescale', label: 'wescale', value: 6 },
    { id: 'ovhcloud', label: 'ovhcloud', value: 6 },
    { id: 'onepoint', label: 'onepoint', value: 5 },
    { id: 'younup', label: 'younup', value: 5 },
    { id: 'freelance', label: 'freelance', value: 4 },
    { id: 'asi', label: 'asi', value: 4 },
    { id: 'bouygues-telecom', label: 'bouygues-telecom', value: 4 },
    { id: 'stack-labs', label: 'stack-labs', value: 4 },
    { id: 'bearstudio', label: 'bearstudio', value: 4 },
    { id: 'shodo', label: 'shodo', value: 4 },
    { id: 'talend', label: 'talend', value: 3 },
    { id: 'niji', label: 'niji', value: 3 },
    { id: 'maif', label: 'maif', value: 3 },
    { id: 'accenture', label: 'accenture', value: 3 },
    { id: 'red-hat', label: 'red-hat', value: 3 },
    { id: 'valeuriad', label: 'valeuriad', value: 3 },
    { id: 'takima', label: 'takima', value: 3 },
    { id: 'elastic', label: 'elastic', value: 2 },
    { id: 'ippon-technologies', label: 'ippon-technologies', value: 2 },
    { id: 'microsoft', label: 'microsoft', value: 2 },
    { id: 'digital-4-better', label: 'digital-4-better', value: 2 },
    { id: 'zenika-rennes', label: 'zenika-rennes', value: 2 },
    { id: 'xebia', label: 'xebia', value: 2 },
    { id: 'gens-de-confiance', label: 'gens-de-confiance', value: 2 },
    { id: 'code-lutin', label: 'code-lutin', value: 2 },
    { id: 'la-poste', label: 'la-poste', value: 2 },
    { id: 'norsys', label: 'norsys', value: 2 },
    { id: 'luos', label: 'luos', value: 2 },
    { id: 'fungus', label: 'fungus', value: 1 },
    { id: 'october', label: 'october', value: 1 },
    { id: 'umbraco-hq', label: 'umbraco-hq', value: 1 },
    { id: 'decathlon', label: 'decathlon', value: 1 },
    { id: 'worldline', label: 'worldline', value: 1 },
    { id: 'hazelcast', label: 'hazelcast', value: 1 },
    { id: 'mb-2-a-technology', label: 'mb-2-a-technology', value: 1 },
    { id: 'nantes-numerique-responsable', label: 'nantes-numerique-responsable', value: 1 },
    { id: 'i-have-a-green', label: 'i-have-a-green', value: 1 },
    { id: 'octo-technology', label: 'octo-technology', value: 1 },
    { id: 'sopra-steria', label: 'sopra-steria', value: 1 },
    { id: 'welovedevs', label: 'welovedevs', value: 1 },
    { id: 'bump-sh', label: 'bump-sh', value: 1 },
    { id: 'amazon-web-services', label: 'amazon-web-services', value: 1 },
    { id: 'mangopay', label: 'mangopay', value: 1 },
    { id: 'vmware', label: 'vmware', value: 1 },
    { id: 'sigma-informatique', label: 'sigma-informatique', value: 1 },
    { id: 'sigma', label: 'sigma', value: 1 },
    { id: 'les-tilleuls-coop', label: 'les-tilleuls-coop', value: 1 },
    { id: 'radio-france', label: 'radio-france', value: 1 },
    {
      id: 'universite-de-nantes-ecole-normale-superieure-de-rennes',
      label: 'universite-de-nantes-ecole-normale-superieure-de-rennes',
      value: 1,
    },
    { id: 'ikobox', label: 'ikobox', value: 1 },
    { id: 'perspectives-visuelles', label: 'perspectives-visuelles', value: 1 },
    { id: 'eladsc-com', label: 'eladsc-com', value: 1 },
    { id: 'automattic', label: 'automattic', value: 1 },
    { id: 'the-tribe', label: 'the-tribe', value: 1 },
    { id: 'one-point', label: 'one-point', value: 1 },
    { id: 'alcatel-lucent-enterprise', label: 'alcatel-lucent-enterprise', value: 1 },
    { id: 'lucca', label: 'lucca', value: 1 },
    { id: 'siradel', label: 'siradel', value: 1 },
    { id: 'sogeti', label: 'sogeti', value: 1 },
    { id: 'palo-it', label: 'palo-it', value: 1 },
    { id: 'elephant-technologie', label: 'elephant-technologie', value: 1 },
    { id: 'capgemini', label: 'capgemini', value: 1 },
    { id: '1985', label: '1985', value: 1 },
    { id: 'cbp', label: 'cbp', value: 1 },
    { id: 'ing', label: 'ing', value: 1 },
    { id: 'sunday', label: 'sunday', value: 1 },
    { id: 'google', label: 'google', value: 1 },
    { id: 'gensdeconfiance', label: 'gensdeconfiance', value: 1 },
    { id: 'lectra', label: 'lectra', value: 1 },
    { id: 'bedrock', label: 'bedrock', value: 1 },
    { id: 'thetribe', label: 'thetribe', value: 1 },
    { id: 'alwaysdata', label: 'alwaysdata', value: 1 },
    { id: 'akeneo', label: 'akeneo', value: 1 },
    { id: 'aircall', label: 'aircall', value: 1 },
    { id: 'sii', label: 'sii', value: 1 },
    { id: 'sercel', label: 'sercel', value: 1 },
    { id: 'typeunsafe', label: 'typeunsafe', value: 1 },
    { id: 'pix', label: 'pix', value: 1 },
    { id: 'amazon-web-services-emea', label: 'amazon-web-services-emea', value: 1 },
    { id: 'harmonie-mutuelle', label: 'harmonie-mutuelle', value: 1 },
    { id: 'thales-services-numeriques', label: 'thales-services-numeriques', value: 1 },
    { id: 'thegaragebandofit', label: 'thegaragebandofit', value: 1 },
    { id: 'spacelephant', label: 'spacelephant', value: 1 },
    { id: 'reea-net', label: 'reea-net', value: 1 },
    { id: 'coffreo', label: 'coffreo', value: 1 },
    { id: 'thales', label: 'thales', value: 1 },
    { id: 'greenspector', label: 'greenspector', value: 1 },
    { id: 'swisslife', label: 'swisslife', value: 1 },
    { id: 'webnet', label: 'webnet', value: 1 },
    { id: 'manomano', label: 'manomano', value: 1 },
    { id: 'promyze', label: 'promyze', value: 1 },
    { id: 'eleven-labs', label: 'eleven-labs', value: 1 },
    { id: 'eni-ecole-informatique', label: 'eni-ecole-informatique', value: 1 },
    { id: 'eni', label: 'eni', value: 1 },
    { id: 'ideolys-carboneio', label: 'ideolys-carboneio', value: 1 },
    { id: 'd-edge', label: 'd-edge', value: 1 },
    { id: 'accenture-technology', label: 'accenture-technology', value: 1 },
    { id: 'ab-tasty', label: 'ab-tasty', value: 1 },
    { id: 'blackrock', label: 'blackrock', value: 1 },
    { id: 'zenika-pix', label: 'zenika-pix', value: 1 },
    { id: 'association-estimnumerique', label: 'association-estimnumerique', value: 1 },
    { id: 'cybelangel', label: 'cybelangel', value: 1 },
    { id: 'mobiapps', label: 'mobiapps', value: 1 },
    { id: 'epfl', label: 'epfl', value: 1 },
  ],
  countriesCount: [{ id: 'unknown', label: 'unknown', value: 287 }],
  proposalsByDate: [
    { day: '2021-06-14', value: 48 },
    { day: '2021-04-01', value: 15 },
    { day: '2021-05-31', value: 3 },
    { day: '2021-05-27', value: 7 },
    { day: '2021-05-18', value: 6 },
    { day: '2021-05-04', value: 9 },
    { day: '2021-04-19', value: 3 },
    { day: '2021-04-18', value: 7 },
    { day: '2021-06-08', value: 4 },
    { day: '2021-04-08', value: 3 },
    { day: '2021-06-04', value: 3 },
    { day: '2021-06-15', value: 67 },
    { day: '2021-06-02', value: 4 },
    { day: '2021-04-07', value: 7 },
    { day: '2021-05-02', value: 1 },
    { day: '2021-04-09', value: 7 },
    { day: '2021-06-11', value: 14 },
    { day: '2021-05-10', value: 2 },
    { day: '2021-04-14', value: 1 },
    { day: '2021-06-07', value: 8 },
    { day: '2021-04-23', value: 3 },
    { day: '2021-05-09', value: 2 },
    { day: '2021-04-16', value: 3 },
    { day: '2021-05-15', value: 2 },
    { day: '2021-04-02', value: 9 },
    { day: '2021-04-27', value: 7 },
    { day: '2021-04-06', value: 4 },
    { day: '2021-06-13', value: 7 },
    { day: '2021-05-22', value: 2 },
    { day: '2021-06-03', value: 1 },
    { day: '2021-05-23', value: 3 },
    { day: '2021-04-29', value: 3 },
    { day: '2021-06-06', value: 4 },
    { day: '2021-06-01', value: 13 },
    { day: '2021-05-05', value: 2 },
    { day: '2021-05-28', value: 5 },
    { day: '2021-05-21', value: 1 },
    { day: '2021-05-19', value: 7 },
    { day: '2021-06-10', value: 6 },
    { day: '2021-06-12', value: 1 },
    { day: '2021-06-05', value: 3 },
    { day: '2021-05-13', value: 1 },
    { day: '2021-04-03', value: 2 },
    { day: '2021-04-22', value: 2 },
    { day: '2021-05-07', value: 2 },
    { day: '2021-05-29', value: 4 },
    { day: '2021-05-26', value: 6 },
    { day: '2021-05-03', value: 2 },
    { day: '2021-05-06', value: 2 },
    { day: '2021-04-28', value: 1 },
    { day: '2021-04-26', value: 1 },
    { day: '2021-05-11', value: 1 },
    { day: '2021-05-12', value: 3 },
    { day: '2021-05-30', value: 1 },
    { day: '2021-04-30', value: 1 },
    { day: '2021-04-04', value: 1 },
    { day: '2021-05-20', value: 1 },
    { day: '2021-05-16', value: 1 },
    { day: '2021-06-09', value: 1 },
  ],
};
