export default {
  proposalsCount: 415,
  speakersCount: 295,
  proposalsBySpeaker: '1.41',
  formatsCount: [
    {
      id: 'e56e30ab-be22-5055-9138-a86a3249c766',
      label: '📣 Conference',
      value: 197,
    },
    {
      id: 'fc2e9afb-3cba-5428-9214-c146862f2a52',
      label: '⚡️ Quickie',
      value: 112,
    },
    { id: 'unknown', label: 'unknown', value: 72 },
    {
      id: 'bc4d1840-d260-5fb6-9e83-f1b0da239793',
      label: '💻 Codelab',
      value: 34,
    },
  ],
  categoriesCount: [
    { id: 'cf75cee3-5ee8-58de-ac77-6bb665a3463d', label: '🌍 Web', value: 104 },
    {
      id: '4fee2bdd-0cf4-5429-945c-42a422577ff5',
      label: '☁️ Cloud & DevOps',
      value: 64,
    },
    {
      id: 'dfa320e4-1f9b-53ee-8c98-3ef48ba81013',
      label: '📱 Mobile & IoT',
      value: 57,
    },
    {
      id: 'febe50ff-d2d9-5400-97de-839c80abc636',
      label: '💡 Discovery ',
      value: 56,
    },
    {
      id: '3e79596d-6302-5601-a027-901bff9e2692',
      label: '📝 Languages',
      value: 40,
    },
    {
      id: 'c97cf20f-aba8-5bcd-9251-72f8c3c536c6',
      label: '🤖 BigData & AI',
      value: 30,
    },
    {
      id: 'b8f42b3e-d1d0-5212-bb39-9dfad1b01661',
      label: '💚 UX / UI',
      value: 24,
    },
    { id: 'unknown', label: 'unknown', value: 22 },
    {
      id: '1e18bcfa-f91a-5ac0-b2f1-ee586837c398',
      label: '🐱‍💻 SECURITY',
      value: 18,
    },
  ],
  companiesCount: [
    { id: '', label: '', value: 36 },
    { id: 'zenika', label: 'zenika', value: 28 },
    { id: 'sfeir', label: 'sfeir', value: 9 },
    { id: 'ippon-technologies', label: 'ippon-technologies', value: 7 },
    { id: 'bouygues-telecom', label: 'bouygues-telecom', value: 7 },
    {
      id: 'fabernovel-technologies',
      label: 'fabernovel-technologies',
      value: 6,
    },
    { id: 'onepoint', label: 'onepoint', value: 5 },
    { id: 'smart-soft', label: 'smart-soft', value: 5 },
    { id: 'google', label: 'google', value: 5 },
    { id: 'talend', label: 'talend', value: 5 },
    { id: 'ovh', label: 'ovh', value: 4 },
    { id: 'freelance', label: 'freelance', value: 4 },
    { id: 'iadvize', label: 'iadvize', value: 4 },
    { id: 'speachme', label: 'speachme', value: 4 },
    { id: 'monkeypatch', label: 'monkeypatch', value: 3 },
    { id: 'serli', label: 'serli', value: 3 },
    { id: 'niji', label: 'niji', value: 3 },
    { id: 'fenikso', label: 'fenikso', value: 3 },
    { id: 'webnet', label: 'webnet', value: 3 },
    { id: 'maif', label: 'maif', value: 3 },
    { id: 'microsoft', label: 'microsoft', value: 3 },
    { id: 'societe-generale', label: 'societe-generale', value: 3 },
    { id: 'octo-technology', label: 'octo-technology', value: 2 },
    { id: 'akeneo', label: 'akeneo', value: 2 },
    { id: 'thales', label: 'thales', value: 2 },
    { id: 'accenture', label: 'accenture', value: 2 },
    { id: 'code-lutin', label: 'code-lutin', value: 2 },
    { id: 'oui-sncf', label: 'oui-sncf', value: 2 },
    { id: 'capgemini', label: 'capgemini', value: 2 },
    { id: 'sogeti', label: 'sogeti', value: 2 },
    { id: 'asmodee-digital', label: 'asmodee-digital', value: 2 },
    { id: 'valeuriad', label: 'valeuriad', value: 2 },
    { id: 'ekito', label: 'ekito', value: 2 },
    { id: 'la-poste', label: 'la-poste', value: 1 },
    { id: 'equinoa', label: 'equinoa', value: 1 },
    { id: 'premedit-running-care', label: 'premedit-running-care', value: 1 },
    { id: 'saagie', label: 'saagie', value: 1 },
    { id: 'soprasteria', label: 'soprasteria', value: 1 },
    { id: 'eleven-labs', label: 'eleven-labs', value: 1 },
    { id: 'yelda', label: 'yelda', value: 1 },
    { id: 'palo-it', label: 'palo-it', value: 1 },
    { id: 'red-hat', label: 'red-hat', value: 1 },
    { id: 'ers', label: 'ers', value: 1 },
    { id: 'gdg-london', label: 'gdg-london', value: 1 },
    { id: 'clever-cloud', label: 'clever-cloud', value: 1 },
    { id: 'sii', label: 'sii', value: 1 },
    { id: 'sii-ouest', label: 'sii-ouest', value: 1 },
    { id: 'viseo', label: 'viseo', value: 1 },
    { id: 'zenika-nantes', label: 'zenika-nantes', value: 1 },
    { id: 'asi', label: 'asi', value: 1 },
    { id: 'sfeir-gdg-nantes', label: 'sfeir-gdg-nantes', value: 1 },
    { id: 'typeunsafe', label: 'typeunsafe', value: 1 },
    { id: 'buffer', label: 'buffer', value: 1 },
    { id: 'eni-service', label: 'eni-service', value: 1 },
    { id: 'digitemis', label: 'digitemis', value: 1 },
    { id: 'grep-to', label: 'grep-to', value: 1 },
    { id: 'gfi-informatique', label: 'gfi-informatique', value: 1 },
    { id: 'alto-labs', label: 'alto-labs', value: 1 },
    { id: 'creative', label: 'creative', value: 1 },
    { id: 'conserto', label: 'conserto', value: 1 },
    { id: 'axa-france', label: 'axa-france', value: 1 },
    { id: 'oniti', label: 'oniti', value: 1 },
    { id: 'the-code-cooperative', label: 'the-code-cooperative', value: 1 },
    { id: 'jellybooks', label: 'jellybooks', value: 1 },
    { id: 'sodifrance', label: 'sodifrance', value: 1 },
    { id: 'methotic-conseil', label: 'methotic-conseil', value: 1 },
    { id: 'xebia-france', label: 'xebia-france', value: 1 },
    { id: 'chicago-pneumatic', label: 'chicago-pneumatic', value: 1 },
    { id: 'ccmbenchmark-groupe', label: 'ccmbenchmark-groupe', value: 1 },
    { id: 'vente-privee', label: 'vente-privee', value: 1 },
    { id: 'bonitasoft', label: 'bonitasoft', value: 1 },
    { id: 'innoq', label: 'innoq', value: 1 },
    { id: 'ippon-technologie', label: 'ippon-technologie', value: 1 },
    { id: 'sonarsource', label: 'sonarsource', value: 1 },
    { id: 'creativ-ceutical', label: 'creativ-ceutical', value: 1 },
    { id: 'cloud-temple', label: 'cloud-temple', value: 1 },
    { id: '1985', label: '1985', value: 1 },
    { id: 'harpp', label: 'harpp', value: 1 },
    { id: 'wescale', label: 'wescale', value: 1 },
    { id: 'pean', label: 'pean', value: 1 },
    { id: 'adduplex', label: 'adduplex', value: 1 },
    {
      id: 'startup-palace-freelance',
      label: 'startup-palace-freelance',
      value: 1,
    },
    { id: 'zenika-rennes', label: 'zenika-rennes', value: 1 },
    { id: 'iadvize-nantes', label: 'iadvize-nantes', value: 1 },
    { id: 'lucca', label: 'lucca', value: 1 },
    { id: 'hey-gul', label: 'hey-gul', value: 1 },
    { id: 'simplabs-gmbh', label: 'simplabs-gmbh', value: 1 },
    {
      id: 'societe-generale-owasp-fundation',
      label: 'societe-generale-owasp-fundation',
      value: 1,
    },
    { id: 'eclipse-foundation', label: 'eclipse-foundation', value: 1 },
    { id: 'raccoon-studio', label: 'raccoon-studio', value: 1 },
    { id: 'rushio-consulting', label: 'rushio-consulting', value: 1 },
    { id: 'vsware', label: 'vsware', value: 1 },
    { id: 'ideolys', label: 'ideolys', value: 1 },
    { id: 'impact', label: 'impact', value: 1 },
    { id: 'gdg-wtm-london', label: 'gdg-wtm-london', value: 1 },
    { id: 'oracle', label: 'oracle', value: 1 },
    { id: 'fluo', label: 'fluo', value: 1 },
    { id: 'yuxi-global', label: 'yuxi-global', value: 1 },
    { id: 'showmax', label: 'showmax', value: 1 },
    { id: 'maltem', label: 'maltem', value: 1 },
    { id: 'moventes', label: 'moventes', value: 1 },
    { id: 'gdg-russia', label: 'gdg-russia', value: 1 },
    { id: 'teads-tv', label: 'teads-tv', value: 1 },
    { id: 'elium', label: 'elium', value: 1 },
    { id: 'lafourchette', label: 'lafourchette', value: 1 },
    { id: 'sf≡ir', label: 'sf≡ir', value: 1 },
    { id: 'neo-4-j', label: 'neo-4-j', value: 1 },
    { id: 'arolla', label: 'arolla', value: 1 },
    { id: '1974', label: '1974', value: 1 },
    { id: 'worldline', label: 'worldline', value: 1 },
    { id: 'elastic', label: 'elastic', value: 1 },
    { id: 'converge-io', label: 'converge-io', value: 1 },
    { id: 'toki', label: 'toki', value: 1 },
    { id: 'troopers', label: 'troopers', value: 1 },
    { id: 'pole-emploi-dsi', label: 'pole-emploi-dsi', value: 1 },
    { id: 'orange', label: 'orange', value: 1 },
    { id: 'orange-labs', label: 'orange-labs', value: 1 },
    { id: 'guillaume-richard', label: 'guillaume-richard', value: 1 },
    { id: 'pole-emploi', label: 'pole-emploi', value: 1 },
    { id: 'tui-group', label: 'tui-group', value: 1 },
    { id: 'knplabs', label: 'knplabs', value: 1 },
    { id: 'cat-amania', label: 'cat-amania', value: 1 },
    { id: 'gandi', label: 'gandi', value: 1 },
    { id: 'na', label: 'na', value: 1 },
    { id: 'nexmo', label: 'nexmo', value: 1 },
    { id: 'innoq-deutschland-gmbh', label: 'innoq-deutschland-gmbh', value: 1 },
    { id: 'bump-sh', label: 'bump-sh', value: 1 },
    { id: 'spotify', label: 'spotify', value: 1 },
    { id: 'ippon-technology', label: 'ippon-technology', value: 1 },
    { id: 'infinum', label: 'infinum', value: 1 },
    { id: 'decalog', label: 'decalog', value: 1 },
    { id: 'evaneos', label: 'evaneos', value: 1 },
    { id: 'shopify', label: 'shopify', value: 1 },
    { id: 'access-42', label: 'access-42', value: 1 },
    { id: 'wiztivi', label: 'wiztivi', value: 1 },
    { id: 'decathlon', label: 'decathlon', value: 1 },
    { id: 'graviteesource', label: 'graviteesource', value: 1 },
    { id: 'freelancer', label: 'freelancer', value: 1 },
    { id: 'nelite-france', label: 'nelite-france', value: 1 },
    { id: 'stack-labs', label: 'stack-labs', value: 1 },
    { id: 'nilhcem', label: 'nilhcem', value: 1 },
    { id: 'shipmnts', label: 'shipmnts', value: 1 },
    { id: 'apside', label: 'apside', value: 1 },
    { id: 'apside-top', label: 'apside-top', value: 1 },
    { id: 'ubimet-gmbh', label: 'ubimet-gmbh', value: 1 },
    { id: 'mr', label: 'mr', value: 1 },
    { id: 'ogury', label: 'ogury', value: 1 },
    { id: 'techyos', label: 'techyos', value: 1 },
    { id: 'auth-0', label: 'auth-0', value: 1 },
    { id: 'auth-0-inc', label: 'auth-0-inc', value: 1 },
    { id: 'editions-eni', label: 'editions-eni', value: 1 },
    { id: 'gitlab', label: 'gitlab', value: 1 },
    {
      id: 'societe-generale-corporate-investment-banking',
      label: 'societe-generale-corporate-investment-banking',
      value: 1,
    },
  ],
  countriesCount: [
    { id: 'FR', label: 'FR', value: 219 },
    { id: 'unknown', label: 'unknown', value: 42 },
    { id: 'GB', label: 'GB', value: 6 },
    { id: 'US', label: 'US', value: 4 },
    { id: 'DE', label: 'DE', value: 4 },
    { id: 'IE', label: 'IE', value: 3 },
    { id: 'NL', label: 'NL', value: 2 },
    { id: 'LU', label: 'LU', value: 2 },
    { id: 'IN', label: 'IN', value: 2 },
    { id: 'CA', label: 'CA', value: 2 },
    { id: 'CZ', label: 'CZ', value: 1 },
    { id: 'LT', label: 'LT', value: 1 },
    { id: 'RU', label: 'RU', value: 1 },
    { id: 'LK', label: 'LK', value: 1 },
    { id: 'SE', label: 'SE', value: 1 },
    { id: 'SI', label: 'SI', value: 1 },
    { id: 'CH', label: 'CH', value: 1 },
    { id: 'BE', label: 'BE', value: 1 },
    { id: 'CO', label: 'CO', value: 1 },
  ],
  proposalsByDate: [
    { day: '2018-07-07', value: 2 },
    { day: '2018-07-05', value: 4 },
    { day: '2018-07-04', value: 1 },
    { day: '2018-06-30', value: 61 },
    { day: '2018-06-29', value: 63 },
    { day: '2018-06-28', value: 24 },
    { day: '2018-06-27', value: 21 },
    { day: '2018-06-26', value: 15 },
    { day: '2018-06-25', value: 22 },
    { day: '2018-06-24', value: 1 },
    { day: '2018-06-22', value: 10 },
    { day: '2018-06-21', value: 6 },
    { day: '2018-06-20', value: 5 },
    { day: '2018-06-19', value: 14 },
    { day: '2018-06-18', value: 12 },
    { day: '2018-06-17', value: 6 },
    { day: '2018-06-16', value: 3 },
    { day: '2018-06-15', value: 4 },
    { day: '2018-06-14', value: 4 },
    { day: '2018-06-13', value: 3 },
    { day: '2018-06-12', value: 2 },
    { day: '2018-06-11', value: 1 },
    { day: '2018-06-10', value: 1 },
    { day: '2018-06-08', value: 7 },
    { day: '2018-06-07', value: 3 },
    { day: '2018-06-05', value: 2 },
    { day: '2018-06-04', value: 5 },
    { day: '2018-06-03', value: 1 },
    { day: '2018-06-02', value: 4 },
    { day: '2018-06-01', value: 2 },
    { day: '2018-05-31', value: 10 },
    { day: '2018-05-30', value: 10 },
    { day: '2018-05-29', value: 4 },
    { day: '2018-05-28', value: 4 },
    { day: '2018-05-27', value: 1 },
    { day: '2018-05-25', value: 3 },
    { day: '2018-05-24', value: 1 },
    { day: '2018-05-23', value: 1 },
    { day: '2018-05-22', value: 10 },
    { day: '2018-05-21', value: 3 },
    { day: '2018-05-20', value: 1 },
    { day: '2018-05-19', value: 1 },
    { day: '2018-05-18', value: 10 },
    { day: '2018-05-17', value: 5 },
    { day: '2018-05-16', value: 1 },
    { day: '2018-05-15', value: 4 },
    { day: '2018-05-14', value: 10 },
    { day: '2018-05-09', value: 1 },
    { day: '2018-05-08', value: 4 },
    { day: '2018-05-07', value: 4 },
    { day: '2018-05-06', value: 2 },
    { day: '2018-05-05', value: 2 },
    { day: '2018-05-04', value: 1 },
    { day: '2018-05-03', value: 3 },
    { day: '2018-05-02', value: 3 },
    { day: '2018-05-01', value: 6 },
    { day: '2018-04-30', value: 1 },
  ],
};
